### ISSUE TITLE
Fields.th(32): error C2338: Invalid function presence detection

### ISSUE THREAD

**Issue by raitraak-rrk** [arobenko/comms_champion#5]
First of all thanks for the awesome library and a nice read!

Trying to compile using the latest MSVC (19.15.26729.0). Getting an error:

FieldsTestRunner.cpp
c:\test\comms_champion\build\comms\test\..\..\..\comms\test\Fields.th(32): error C2338: Invalid function presence detection

Any ideas?

**Comment by arobenko** [comment]
It looks like you are using VS2017. Myself, I use Linux as my primary development environment and use "appveyor" to compile my project on Windows with Visual Studio compiler. Recently I tried to use their VS2017 image and got unexpected compilation errors, that's why I recently introduced this static_assert checks.

In the COMMS library I use meta-programming tricks with SFINAE to check the presence of some functions in various storage types. The mentioned error checks that **std::string** has "resize(size_type)" function. This check works fine with VS2015, but fails with VS2017. The [cppreference](https://en.cppreference.com/w/cpp/string/basic_string/resize) page doesn't show any changes to function signature that could cause this error.

The "appveyor" environment doesn't use latest release of VS2017 and I haven't had the chance to download it myself and check whether the problem has been fixed. In case the problem persists, error report should be sent to Microsoft.

The SFINAE code that performs the check can be found [here](https://github.com/arobenko/comms_champion/blob/master/comms/include/comms/details/detect.h#L109). I encourage you to copy this small piece of code to a separate small project and compile it with VS2015 (should work) and latest release of VS2017. If the latter fails please let me know and I will file a bug report to VS development team, or you are welcome to do it yourself.

Regards,
Alex

**Comment by raitraak-rrk** [comment]
Apparently the basic_string implementation in the latest version does not overload resize method. Only the following is defined:

void resize(_CRT_GUARDOVERFLOW const size_type _Newsize, const _Elem _Ch = _Elem())
		{	// determine new length, padding with _Ch elements as needed
		const size_type _Old_size = size();
		if (_Newsize <= _Old_size)
			{
			_Eos(_Newsize);
			}
		else
			{
			append(_Newsize - _Old_size, _Ch);
			}
		}


Is this a bug? From regular usage perspective it doesn't break anything.

**Comment by arobenko** [comment]
I'd say it deviates from C++ specification which defines it to be 2
separate functions instead of 1 unified. I will submit a report to
Microsoft and see what they reply, then I decide how to proceed with VS2017
support. In the meantime I recommend you use VS2015. It should work fine.

**Comment by arobenko** [comment]
The report to Microsoft is [here](https://developercommunity.visualstudio.com/content/problem/334130/regression-in-vs2017-vs-vs2015-when-detecting-pres.html)

**Comment by arobenko** [comment]
It looks like MS will keep their STD library as is without any changes. I'll have to workaround this bug. Solution should be ready in a couple of days.

**Comment by arobenko** [comment]
I think I found the way to detect a presence of the "resize" function that will work on all the compilers. Fix is currently available on "debug" branch. I'll release it within a week or two.

Thanks for the report and help in analysis of the reason.

**Comment by raitraak-rrk** [comment]
Thanks!
